version: 0.0
os: linux
files:
  - source: /
    destination: /var/cardsite
hooks:
  BeforeInstall:
    - location: scripts/install_deps.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
