version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - sbt dist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/universal/cardsite-1.0-SNAPSHOT.zip
