package games

import Rank._
import Suit._

object Deck {
  val defaultDeck = List(
    Card(Hearts, Two),
    Card(Hearts, Three),
    Card(Hearts, Four),
    Card(Hearts, Five),
    Card(Hearts, Six),
    Card(Hearts, Seven),
    Card(Hearts, Eight),
    Card(Hearts, Nine),
    Card(Hearts, Ten),
    Card(Hearts, Jack),
    Card(Hearts, Queen),
    Card(Hearts, King),
    Card(Hearts, Ace),
    Card(Clubs, Two),
    Card(Clubs, Three),
    Card(Clubs, Four),
    Card(Clubs, Five),
    Card(Clubs, Six),
    Card(Clubs, Seven),
    Card(Clubs, Eight),
    Card(Clubs, Nine),
    Card(Clubs, Ten),
    Card(Clubs, Jack),
    Card(Clubs, Queen),
    Card(Clubs, King),
    Card(Clubs, Ace),
    Card(Hearts, Two),
    Card(Hearts, Three),
    Card(Hearts, Four),
    Card(Hearts, Five),
    Card(Hearts, Six),
    Card(Hearts, Seven),
    Card(Hearts, Eight),
    Card(Hearts, Nine),
    Card(Hearts, Ten),
    Card(Hearts, Jack),
    Card(Hearts, Queen),
    Card(Hearts, King),
    Card(Hearts, Ace),
    Card(Hearts, Two),
    Card(Hearts, Three),
    Card(Hearts, Four),
    Card(Hearts, Five),
    Card(Hearts, Six),
    Card(Hearts, Seven),
    Card(Hearts, Eight),
    Card(Hearts, Nine),
    Card(Hearts, Ten),
    Card(Hearts, Jack),
    Card(Hearts, Queen),
    Card(Hearts, King),
    Card(Hearts, Ace)
  )
}
